# coding = utf - 8
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
# 前十条团队创建十个成员
def cjcy():
    driver = webdriver.Chrome()
    driver.get('https://learn.dev.longan.eliteu.xyz/manage/team/')
    driver.maximize_window()
    driver.find_element_by_xpath('//*[@id="normal_login_username"]').send_keys('abc')
    sleep(1)
    driver.find_element_by_xpath('//*[@id="normal_login_password"]').send_keys('123456')
    sleep(1)
    driver.find_element_by_xpath('//*[@id="normal_login"]/div[4]/div/div/div/button').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(2)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[3]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[4]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[5]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[6]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[7]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[8]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="team"]/div[1]/div[2]/div/div/div/ul/li[4]/a').click()
    sleep(2)
    driver.refresh()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="team"]/div[1]/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[1]/span').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[3]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[1]/div/textarea').send_keys('小一',
                                                                                                               Keys.ENTER,
                                                                                                               '小二',
                                                                                                               Keys.ENTER,
                                                                                                               '小三',
                                                                                                               Keys.ENTER,
                                                                                                               '小四',
                                                                                                               Keys.ENTER,
                                                                                                               '小五',
                                                                                                               Keys.ENTER,
                                                                                                               '小六',
                                                                                                               Keys.ENTER,
                                                                                                               '小七',
                                                                                                               Keys.ENTER,
                                                                                                               '小八',
                                                                                                               Keys.ENTER,
                                                                                                               '小九',
                                                                                                               Keys.ENTER,
                                                                                                               '小十', )
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[2]/div[2]/div/div[2]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="teamItem"]/div[1]/div[4]/div[2]/div/button[1]').click()
    sleep(1)
    driver.back()
    sleep(1)
    driver.refresh()
    sleep(3)
    driver.quit()