# coding = utf - 8
from selenium import webdriver
from time import sleep
# 删除前十条作品集
def tjzp():
    options=webdriver.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["ignore-certificate-errors"])
    driver = webdriver.Chrome(chrome_options=options)
    driver.get('https://learn.dev.longan.eliteu.xyz/manage/portfolio/')
    driver.maximize_window()
    sleep(1)
    driver.find_element_by_xpath('//*[@id="normal_login_username"]').send_keys('abc')
    sleep(1)
    driver.find_element_by_xpath('//*[@id="normal_login_password"]').send_keys('123456')
    sleep(1)
    driver.find_element_by_xpath('//*[@id="normal_login"]/div[4]/div/div/div/button').click()

    # 第一个
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[1]/a/span').click()
    sleep(1)
    driver.refresh()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(4)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()

    # 第二个作品集
    sleep(3)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(2)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()

    # 第三个作品集
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[3]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(2)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()

    # 第四个作品集
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[4]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(2)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()

    # 第五个
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[5]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(2)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(2)
    driver.back()

    # 第六个
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[6]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(2)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()

    # 第七个
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[7]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(2)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()

    # 第八个
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[8]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(2)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()

    # 第九个
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath('//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/ul/li[4]').click()
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(4)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()

    # 第十个
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolio"]/div[1]/section/div[2]/div/div/div/div/div/div/table/tbody/tr[2]/td[1]/a/span').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[1]/div[2]/div[1]/div/div[1]/div[2]/button').click()
    sleep(1)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(2)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(5)

    # 下一页
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[4]/ul/li[5]/a').click()
    sleep(3)
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[1]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[2]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[3]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[4]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[5]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[6]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[7]/div[1]').click()
    driver.find_element_by_xpath(
        '//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[1]/div/div[3]/div[8]/div[1]').click()
    sleep(2)
    # 点击完成
    driver.find_element_by_xpath('//*[@id="portfolioItem"]/div[2]/div[2]/div/div[2]/div[2]/div/button[2]').click()
    sleep(3)
    driver.back()
    sleep(2)
    driver.refresh()
    sleep(2)
    driver.quit()